describe('Meal suggestion', () => {
  beforeEach(() => {
    if (Cypress.env('environment') === 'prod') {
      cy.visit('https://meal-suggestion.s3.eu-central-1.amazonaws.com/index.html')
    } else {
      cy.visit('./src/index.html')
    }
    cy.title().should('be.equal', 'Sugestão de Refeição Vegana')
    cy.contains('h1', 'Refeição vegana 🌱')
      .as('heading')
      .should('be.visible')
    cy.contains('#filter-container label', 'Tipo:').should('be.visible')
    cy.get('#meal-type-filter')
      .as('filterSelectField')
      .should('be.visible')
      .and('have.value', 'all')
    cy.contains('#search-container label', 'Busca:').should('be.visible')
    cy.get('#search-field')
      .as('searchField')
      .should('be.visible')
    cy.get('#search-container button')
      .as('searchButton')
      .should('be.visible')
    cy.contains('#meal-name', 'Refeição: ')
      .as('mealName')
      .should('be.visible')
    cy.contains('#ingredients-label', 'Ingredientes:')
      .as('ingredientsLabel')
      .should('be.visible')
    cy.get('ul li')
      .as('ingredients')
      .should('be.visible')
      .its('length')
      .should('be.at.least', 1)
    cy.contains('button', 'Outra sugestão')
      .as('button')
      .should('be.visible')
    cy.get('body').should('have.css', 'background-color', 'rgb(254, 246, 228)')
  })

  it('shows one of all meal suggestions', () => {
    cy.get('@button')
      .click()
      .blur()

    cy.get('@mealName').should('be.visible')
    cy.get('@ingredientsLabel').should('be.visible')
    cy.get('@ingredients')
      .should('be.visible')
      .its('length')
      .should('be.at.least', 1)
  })

  it('shows a filtered meal suggestion', () => {
    cy.get('@filterSelectField').select('Saladas')

    cy.get('@mealName')
      .should('be.visible')
      .and('contain', ' (salada)')
    cy.get('@ingredientsLabel').should('be.visible')
    cy.get('@ingredients')
      .should('be.visible')
      .its('length')
      .should('be.at.least', 1)
  })

  it('searches for a meal by typing and clicking the submit button', () => {
    cy.get('@searchField').type('Ramen')
    cy.get('@searchButton')
      .click()
      .blur()

    cy.get('@mealName')
      .should('be.visible')
      .and('contain', 'Ramen (sopa)')
    cy.get('@ingredientsLabel').should('be.visible')
    cy.get('@ingredients')
      .should('be.visible')
      .and('contain', 'massa de ramen')
      .and('contain', 'brócolis')
      .and('contain', 'cenoura')
      .and('contain', 'edamame')
      .and('contain', 'tofu')
      .and('contain', 'cebolinha')
      .and('contain', 'misô')
      .and('contain', 'milho')
      .its('length')
      .should('equal', 8)
  })

  it('makes sure trim works when searching', () => {
    cy.get('@searchField').type('pepino    ')
    cy.get('@searchButton')
      .click()
      .blur()

    cy.get('@mealName')
      .should('be.visible')
      .and('contain', 'pepino (sanduíche)')
    cy.get('@ingredientsLabel').should('be.visible')
    cy.get('@ingredients')
      .should('be.visible')
      .and('contain', 'humus ou margarina')
      .and('contain', 'pão francês')
      .and('contain', 'tomate')
      .and('contain', 'pepino')
      .and('contain', 'pimenta do reino')
      .its('length')
      .should('equal', 5)
  })

  it('searches for a meal by typing and pressing ENTER', () => {
    cy.get('@searchField')
      .type('Ramen{enter}')
      .blur()

    cy.get('@mealName')
      .should('be.visible')
      .and('contain', 'Ramen (sopa)')
    cy.get('@ingredientsLabel').should('be.visible')
    cy.get('@ingredients')
      .should('be.visible')
      .and('contain', 'massa de ramen')
      .and('contain', 'brócolis')
      .and('contain', 'cenoura')
      .and('contain', 'edamame')
      .and('contain', 'tofu')
      .and('contain', 'cebolinha')
      .and('contain', 'misô')
      .and('contain', 'milho')
      .its('length')
      .should('equal', 8)
  })

  it('searches for a meal by part of its name', () => {
    cy.get('@searchField')
      .type('Ram{enter}')
      .blur()

    cy.get('@mealName')
      .should('be.visible')
      .and('contain', 'Ramen (sopa)')
    cy.get('@ingredientsLabel').should('be.visible')
    cy.get('@ingredients')
      .should('be.visible')
      .and('contain', 'massa de ramen')
      .and('contain', 'brócolis')
      .and('contain', 'cenoura')
      .and('contain', 'edamame')
      .and('contain', 'tofu')
      .and('contain', 'cebolinha')
      .and('contain', 'misô')
      .and('contain', 'milho')
      .its('length')
      .should('equal', 8)
  })

  it('filters and searches for a meal', () => {
    cy.get('@filterSelectField').select('Sopas')
    cy.get('@searchField')
      .type('Ramen{enter}')
      .blur()

    cy.get('@mealName')
      .should('be.visible')
      .and('contain', 'Ramen (sopa)')
    cy.get('@ingredientsLabel').should('be.visible')
    cy.get('@ingredients')
      .should('be.visible')
      .and('contain', 'massa de ramen')
      .and('contain', 'brócolis')
      .and('contain', 'cenoura')
      .and('contain', 'edamame')
      .and('contain', 'tofu')
      .and('contain', 'cebolinha')
      .and('contain', 'misô')
      .and('contain', 'milho')
      .its('length')
      .should('equal', 8)
  })

  it('filters and searches for a meal (negative scenario)', () => {
    cy.get('@filterSelectField').select('Sopas')
    cy.get('@searchField')
      .type('Iron Energy{enter}')
      .blur()

    cy.get('@mealName')
      .should('be.visible')
      .and('contain', ' (sopa)')
    cy.get('@ingredientsLabel').should('be.visible')
    cy.get('@ingredients')
      .should('be.visible')
      .its('length')
      .should('be.at.least', 1)
  })

  it('shows h1 centralized on mobile viewport', { viewportWidth: 400 }, () => {
    cy.get('@heading').should('have.css', 'text-align', 'center')
  })
})
